const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const vm = require('node:vm');
const root = fs.mkdtempSync(path.join(os.tmpdir(),'notus-resource-refresh-'));
Object.assign(process.env,{NOTUS_RUNTIME_TARGET:'web',NOTUS_DATA_ROOT:root,NOTES_DIR:path.join(root,'notes'),ASSETS_DIR:path.join(root,'assets'),DB_PATH:path.join(root,'db.sqlite'),LOG_DIR:path.join(root,'logs'),NOTUS_AGENT_RUNTIME_MODE:'profile'});
let request;
const llmPath=require.resolve('../lib/llm');
require.cache[llmPath]={id:llmPath,filename:llmPath,loaded:true,exports:{completeToolChat:async (input)=>{request=input;return {content:[{type:'text',text:'done'}]};}}};
(async()=>{
 const {getDb}=require('../lib/db');const db=getDb();
 const {ensureConversation}=require('../lib/conversations');
 const {createSession,getSession}=require('../lib/agentSession');
 const {createTask,wakeTask,updateTask}=require('../lib/agentTaskQueue');
 const {skillRoots,listSkills,setSkillEnabled,loadSkill,stopSkillWatchers}=require('../lib/skills');
 const {runAgentLoop}=require('../lib/agentLoop');
 const cid=ensureConversation({kind:'agent',title:'resource test'}).id;
 const sid=createSession({goal:'整理研究笔记',conversationId:cid,authorizedPaths:[''],mcpSelection:{mode:'off'}}).sessionId;
 const originalTask=createTask({sessionId:sid,conversationId:cid});updateTask(sid,{status:'waiting_retry'});
 wakeTask(sid,{toolPreferences:{mcp_selection:{mode:'auto'},web_search_enabled:true,search_provider:'new-provider',allow_local_http:true}});
 assert.equal(getSession(sid).mcp_selection.mode,'auto');assert.equal(getSession(sid).web_search_enabled,true);
 assert.equal(getSession(sid).web_search_provider,'new-provider');assert.equal(getSession(sid).mcp_session_permissions.allow_local_http,undefined);
 wakeTask(sid,{toolPreferences:{mcp_selection:{mode:'off'},web_search_enabled:false}});
 assert.equal(getSession(sid).mcp_selection.mode,'auto','重复唤醒不能覆盖已入队配置');
 updateTask(sid,{status:'running'});wakeTask(sid,{toolPreferences:{mcp_selection:{mode:'off'}}});assert.equal(getSession(sid).mcp_selection.mode,'auto');
 updateTask(sid,{status:'waiting_retry'});wakeTask(sid,{toolPreferences:{mcp_selection:{mode:'off'},web_search_enabled:false}});assert.equal(getSession(sid).web_search_enabled,false);assert.equal(getSession(sid).mcp_selection.mode,'off');
 const {composeTurnFrame}=require('../lib/agentSemanticRuntime');
 const frameOptions={task:originalTask,session:getSession(sid),userQuery:'解释一下这个概念',allowSemanticPlanner:false};
 const firstFrame=(await composeTurnFrame({...frameOptions,webSearchEnabled:false})).frame;
 const currentFrame=(await composeTurnFrame({...frameOptions,webSearchEnabled:true})).frame;
 assert.equal(currentFrame.id,firstFrame.id);assert.equal(currentFrame.intent.source_policy.web,'allowed');
 assert.equal((await composeTurnFrame({...frameOptions,webSearchEnabled:false})).frame.intent.source_policy.web,'forbidden');
 const dir=path.join(skillRoots()[0].path,'fresh-skill');fs.mkdirSync(dir,{recursive:true});
 const writeSkill=(version)=>fs.writeFileSync(path.join(dir,'SKILL.md'),`---\nname: fresh-skill\ndescription: Fresh ${version}\n---\nBody ${version}\n`);
 const run=async(frame)=>{const id=createSession({goal:'整理研究笔记',conversationId:cid,authorizedPaths:['']}).sessionId;await runAgentLoop({sessionId:id,llmConfig:{llmContextWindowTokens:60000},turnFrame:frame});return request;};
 writeSkill('v1');let req=await run();assert.ok(JSON.stringify(req).includes('Fresh v1'));let skill=listSkills().find(s=>s.name==='fresh-skill');assert.ok(skill);const hash=skill.content_hash;
 writeSkill('v2');req=await run();assert.ok(JSON.stringify(req).includes('Fresh v2'));assert.ok(!JSON.stringify(req).includes('Fresh v1'));skill=listSkills().find(s=>s.name==='fresh-skill');assert.notEqual(skill.content_hash,hash);assert.ok(loadSkill(skill.id).instructions.includes('Body v2'));
 setSkillEnabled(skill.id,false);req=await run();assert.ok(!JSON.stringify(req).includes('Fresh v2'));
 const {projectToolDefinitions}=require('../lib/agentToolProfile');const mcpTool={name:'mcp_search',mcp:{serverId:'s',toolName:'search'},input_schema:{type:'object'}};
 for(const kind of ['web_research','skill_discovery']) assert.ok(projectToolDefinitions([mcpTool],{intent:{task_kind:kind,source_policy:{web:'required'}}}).some(t=>t.name==='mcp_search'));
 // Exercise actual discovery implementation against a changing server, including stale-cache failures.
 const src=fs.readFileSync(require.resolve('../lib/mcp'),'utf8');const a=src.indexOf('async function prepareMcpTools');const b=src.indexOf('\nasync function ',a+1);
 let schema='old',calls=0,fail=false;const server={id:'s',name:'Search'};
 const ctx={listServers:()=>[server],isLocalHttpServer:()=>false,isToolCacheStale:()=>false,refreshTools:async()=>{calls++;if(fail)throw Error('offline');schema='new';},cachedTools:()=>[{tool_name:'search',description:'search',input_schema:{type:'object',properties:{[schema]:{type:'string'}}}}],intentTerms:()=>[],MAX_AUTO_SERVERS:5,MAX_AUTO_TOOLS:20,connections:new Map(),connectionKey:()=>'',alias:()=> 'mcp_search'};
 vm.createContext(ctx);vm.runInContext(src.slice(a,b),ctx);
 assert.equal((await ctx.prepareMcpTools({mode:'off'},'',{},{forceRefresh:true})).tools.length,0);assert.equal(calls,0);
 let tools=(await ctx.prepareMcpTools({mode:'auto'},'',{},{forceRefresh:true})).tools;assert.ok(tools[0].input_schema.properties.new);assert.equal(calls,1);
 fail=true;assert.equal((await ctx.prepareMcpTools({mode:'auto'},'',{},{forceRefresh:true})).tools.length,0);
 stopSkillWatchers();db.close();fs.rmSync(root,{recursive:true,force:true});console.log('resource refresh: queue guards, live Skill install/update/disable, MCP discovery and web projection passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
