const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'notus-materials-'));
Object.assign(process.env, { NOTUS_RUNTIME_TARGET: 'web', NOTUS_DATA_ROOT: root, DB_PATH: path.join(root,'db.sqlite'), NOTES_DIR: path.join(root,'notes'), ASSETS_DIR: path.join(root,'assets') });
async function main() {
  const { getDb } = require('../lib/db');
  // Indexing is outside this test; keep image preview/apply on real files and SQLite.
  require('../lib/indexer').triggerIncrementalIndex = async () => ({});
  const { ensureConversation, appendConversationMessage } = require('../lib/conversations');
  const { createSession, getSession } = require('../lib/agentSession');
  const { createTask } = require('../lib/agentTaskQueue');
  const { getImagesDir, makeConversationImageReference } = require('../lib/conversationImages');
  const { saveAttachment } = require('../lib/parsedAttachmentStore');
  const { listMaterials, readAttachment, materialDirectoryPrompt } = require('../lib/agentMaterials');
  const { listFileImages, resolveImage, inspectImage } = require('../lib/agentVision');
  const { createFile, updateFile } = require('../lib/files');
  const { executeToolSafely, buildToolDefinitions } = require('../lib/agentTools');
  const { projectToolDefinitions } = require('../lib/agentToolProfile');
  const { evictOldReadWindows } = require('../lib/agentMessageProjection');
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64');
  const cid = ensureConversation({kind:'canvas',title:'五图测试'}).id;
  fs.mkdirSync(getImagesDir(), {recursive:true});
  fs.mkdirSync(path.join(root,'notes'), {recursive:true});
  fs.mkdirSync(path.join(root,'assets'), {recursive:true});
  const images = Array.from({length:5}, (_,i) => ({ id:`image-${i}`, name:'image.png', stored_name:`image-${i}.png`, extension:'.png', upload_order:i }));
  images.forEach(image => fs.writeFileSync(path.join(getImagesDir(),image.stored_name),png));
  const first = appendConversationMessage({conversationId:cid,role:'user',content:'把五张截图放在对应功能段落',meta:{images}});
  let calls = 0;
  const llm = require('../lib/llm');
  const original = llm.completeToolChat;
  llm.completeToolChat = async request => {
    calls++;
    const blocks = request.messages[0].content.filter(b=>b.type==='image');
    assert.equal(blocks.length,1,'逐图进入真实视觉块');
    assert.equal(blocks[0].source.data,png.toString('base64'));
    return {content:[{type:'text',text:`功能界面 ${calls}`}], usage:{input_tokens:10,output_tokens:5,total_tokens:15}};
  };
  delete require.cache[require.resolve('../lib/imageRecognition')];
  const { recognizeConversationImages } = require('../lib/imageRecognition');
  const recognized = await recognizeConversationImages({conversationId:cid,messageId:first,images});
  assert.equal(recognized.recognizedCount,5); assert.equal(calls,5);
  assert.equal(recognized.usage.total_tokens,75);
  for(let i=0;i<5;i++) assert.ok(recognized.text.includes(`功能界面 ${i+1}`));
  await recognizeConversationImages({conversationId:cid,messageId:first,images}); assert.equal(calls,5,'恢复复用逐图结果');
  const aid = saveAttachment(cid,{source:'long.txt',text:'正文'.repeat(8000)+'唯一尾部',type:'plaintext'},{sourceMessageId:first});
  const current = appendConversationMessage({conversationId:cid,role:'user',content:'重排历史截图并读取附件结尾'});
  const {sessionId}=createSession({conversationId:cid,goal:'重排历史截图'});
  createTask({sessionId,conversationId:cid,userMessageId:current});
  const session=getSession(sessionId);
  assert.equal(listMaterials(session).total,11);
  assert.equal(listMaterials(session,{offset:10,limit:1}).items.length,1);
  assert.ok(materialDirectoryPrompt(session).includes('inspect_image'));
  const attachment=readAttachment(session,{ref:`attachment://${aid}`,offset:16000});
  assert.equal(attachment.content,'唯一尾部'); assert.equal(attachment.next_offset,null);
  const ref=makeConversationImageReference(first,images[3].id);
  assert.equal((await resolveImage(session,{ref})).source.data,png.toString('base64'));
  const other=ensureConversation({kind:'canvas',title:'其他对话'}).id;
  assert.equal(readAttachment({...session,conversation_id:other},{ref:`attachment://${aid}`}).error,'ATTACHMENT_NOT_FOUND');
  await assert.rejects(resolveImage({...session,conversation_id:other},{ref}),/CONVERSATION_IMAGE_NOT_FOUND/);
  const future=appendConversationMessage({conversationId:cid,role:'user',content:'未来',meta:{images:[images[0]]}});
  saveAttachment(cid,{source:'future.txt',text:'未来附件',type:'plaintext'},{sourceMessageId:future});
  assert.equal(listMaterials(session).total,11);
  await assert.rejects(resolveImage(session,{ref:makeConversationImageReference(future,images[0].id)}),/CONVERSATION_IMAGE_NOT_FOUND/);
  const data=`data:image/png;base64,${png.toString('base64')}`;
  // A large embedded image stays a short model reference and survives an actual preview/apply round trip.
  const embedded = createFile('embedded.md', `# Embedded\n\n![图](data:image/png;base64,${png.toString('base64').repeat(5000)})\n\n文章末尾标记`);
  const projected = require('../lib/agentTools').executeReadFile({path:embedded.path});
  assert.ok(projected.content.includes('note-image://') && projected.content.includes('文章末尾标记'));
  assert.ok(!projected.content.includes('base64'));
  assert.equal(projected.truncated,false);
  const longIdContent = require('../lib/agentVision').projectFileImages({...embedded,id:9907892});
  assert.equal(require('../lib/agentToolPolicy').limitToolResult('read_file',{content:longIdContent}).content,longIdContent,'长文件ID与哈希引用不能被密钥脱敏破坏');

  const rows = projected.content.split('\n');
  const moved = rows.filter(line=>!line.startsWith('![')).join('\n')+'\n'+rows.find(line=>line.startsWith('!['));
  const preview = await executeToolSafely({id:'move-embedded',name:'preview_file_revision',input:{file_path:embedded.path,draft_content:moved}},session);
  assert.ok(preview.operation_set_id,JSON.stringify(preview));
  const operation = getDb().prepare('SELECT revision_draft_content FROM canvas_operation_sets WHERE id=?').get(preview.operation_set_id);
  assert.ok(operation.revision_draft_content.includes('base64') && !operation.revision_draft_content.includes('note-image://'));
  const applied = await require('../lib/fileRevisions').applyFileRevision(preview.operation_set_id,session.id);
  assert.ok(applied.applied,JSON.stringify(applied));
  const saved = require('../lib/files').getFileById(embedded.id).content;
  assert.ok(saved.indexOf('文章末尾标记') < saved.indexOf('![图]'));
  assert.ok(saved.includes(png.toString('base64').repeat(5000)));

  // Remote paths with long entropy are projected before redaction, then restored byte for byte.
  const url = `https://example.com/${'abcdef0123456789'.repeat(6)}.png?signature=keep-exact`;
  const remote = createFile('remote.md', `# Remote\n\n![图](${url})`);
  const readRemote = require('../lib/agentTools').executeReadFile({path:remote.path});
  const safeRead = require('../lib/agentToolPolicy').limitToolResult('read_file',readRemote);
  assert.ok(!safeRead.content.includes('REDACTED') && !safeRead.content.includes(url));
  const remotePreview = await executeToolSafely({id:'rewrite-remote',name:'preview_file_revision',input:{file_path:remote.path,draft_content:safeRead.content.replace('# Remote','# 改写')}},session);
  assert.ok(remotePreview.operation_set_id,JSON.stringify(remotePreview));
  const remoteOp = getDb().prepare('SELECT revision_draft_content FROM canvas_operation_sets WHERE id=?').get(remotePreview.operation_set_id);
  assert.ok(remoteOp.revision_draft_content.includes(url));
  const wrongDraft = `# 改写\n![图](https://example.com/guessed.png)`;
  const blocked = await executeToolSafely({id:'bad-rewrite',name:'preview_file_revision',input:{file_path:remote.path,draft_content:wrongDraft}},session);
  assert.equal(blocked.error,'IMAGE_SOURCE_CHANGE_REQUIRES_INTENT');
  const patchBlocked = await executeToolSafely({id:'bad-patch',name:'preview_patch_files',input:{patches:[{file_path:remote.path,old:safeRead.content,new:wrongDraft}]}},session);
  assert.equal(patchBlocked.error,'IMAGE_SOURCE_CHANGE_REQUIRES_INTENT');
  const malformed = await executeToolSafely({id:'bad-create',name:'create_note',input:{path:'invalid.md',content:'![图](https://example.com/[REDACTED].png)'}},session);
  assert.equal(malformed.error,'IMAGE_REFERENCE_INVALID');
  const snapshots = listFileImages({path:remote.path},session).snapshots;
  assert.ok(snapshots.some(row=>row.operation_set_id===remotePreview.operation_set_id));
  const history = listFileImages({path:remote.path,operation_set_id:remotePreview.operation_set_id},session);
  assert.ok(history.items[0].ref.startsWith('note-snapshot-image://'));
  const {restoreFileImageReferences} = require('../lib/agentVision');
  assert.equal(restoreFileImageReferences(history.items[0].ref,session),url);
  assert.throws(()=>restoreFileImageReferences(history.items[0].ref,{...session,conversation_id:other}),/IMAGE_SNAPSHOT_NOT_FOUND/);
  updateFile(remote.id,wrongDraft);
  assert.throws(()=>restoreFileImageReferences(listFileImages({path:embedded.path}).items[0].ref.replace(/\/0$/, '/999'),session),/IMAGE_REFERENCE_INVALID/);
  const restore = await executeToolSafely({id:'restore-image',name:'preview_file_revision',input:{file_path:remote.path,draft_content:`# 保留新正文\n![图](${history.items[0].ref})`,allow_image_changes:true}},session);
  assert.ok(restore.operation_set_id,JSON.stringify(restore));
  updateFile(remote.id,wrongDraft+'\n用户并发编辑');
  const conflicted = await require('../lib/fileRevisions').applyFileRevision(restore.operation_set_id,session.id);
  assert.ok(!conflicted.applied,'生成恢复 Diff 后的并发编辑不能被覆盖');
  assert.ok(require('../lib/files').getFileById(remote.id).content.includes('用户并发编辑'));

  const freshRestore = await executeToolSafely({id:'restore-image-fresh',name:'preview_file_revision',input:{file_path:remote.path,draft_content:`# 保留新正文\n用户并发编辑\n![图](${history.items[0].ref})`,allow_image_changes:true}},session);
  assert.ok((await require('../lib/fileRevisions').applyFileRevision(freshRestore.operation_set_id,session.id)).applied);
  assert.ok(require('../lib/files').getFileById(remote.id).content.includes(url));
  assert.ok(require('../lib/files').getFileById(remote.id).content.includes('用户并发编辑'));

  const file=createFile('article.md',`# 文章\n\n![内嵌](${data})\n\n![本地](picture.png)\n\n![图床](https://example.com/image.png)`);
  fs.writeFileSync(path.join(root,'notes','picture.png'),png);
  const listed=listFileImages({path:file.path});
  assert.equal(listed.total,3); assert.ok(!JSON.stringify(listed).includes('base64'));
  for(const item of listed.items.slice(0,2)) assert.equal((await resolveImage(session,{ref:item.ref,path:file.path})).source.data,png.toString('base64'));
  const seen=await inspectImage(session,{ref:listed.items[0].ref,path:file.path});assert.equal(seen.status,'recognized');
  const tools = require('../lib/agentTools');
  const realFetch=tools.fetchPublicWebPage;
  const realCheck=tools.publicWebUrl;
  let networkCalls=0;
  tools.publicWebUrl=async url => url.startsWith('https://example.com/')?{url}:{error:'URL_PRIVATE_NETWORK_BLOCKED'};
  tools.fetchPublicWebPage=async () => {networkCalls++;return new Response(png,{headers:{'content-type':'image/png'}});};
  assert.equal((await resolveImage(session,{ref:listed.items[2].ref,path:file.path})).source.data,png.toString('base64'));
  tools.fetchPublicWebPage=async()=>{networkCalls++;return new Response(null,{status:302,headers:{location:'http://127.0.0.1/internal.png'}});};
  await assert.rejects(resolveImage(session,{ref:listed.items[2].ref,path:file.path}),/URL_PRIVATE_NETWORK_BLOCKED/);
  assert.equal(networkCalls,2,'重定向内网被阻断，未建立第二次连接');
  tools.fetchPublicWebPage=realFetch;tools.publicWebUrl=realCheck;
  fs.writeFileSync(path.join(root,'outside.png'),png);
  fs.symlinkSync(path.join(root,'outside.png'),path.join(root,'notes','escape.png'));
  updateFile(file.id,'![越界](escape.png)');
  await assert.rejects(resolveImage(session,{ref:listed.items[0].ref,path:file.path}),/IMAGE_REFERENCE_STALE/);
  await assert.rejects(resolveImage(session,{ref:listFileImages({path:file.path}).items[0].ref,path:file.path}),/IMAGE_PATH_FORBIDDEN/);
  for(const mode of ['general','file_write','file_read','web_research']) {
    const names=projectToolDefinitions(buildToolDefinitions(session),{intent:{task_kind:mode}}).map(t=>t.name);
    for(const name of ['list_materials','read_attachment','list_file_images','inspect_image']) assert.ok(names.includes(name));
  }
  const read=await executeToolSafely({id:'read1',name:'read_attachment',input:{ref:`attachment://${aid}`,offset:16000}},session);
  assert.equal(read.content,'唯一尾部');
  const windows=evictOldReadWindows([{role:'user',content:'任务'},{role:'assistant',content:[{type:'tool_use',id:'r',name:'read_attachment',input:{ref:`attachment://${aid}`}}]},{role:'user',content:[{type:'tool_result',tool_use_id:'r',content:JSON.stringify(read)}]},...Array.from({length:5},()=>({role:'assistant',content:[]}))]);
  assert.ok(windows[2].content[0].content.includes('唯一尾部'), '预算充足时保留已读取的附件事实');
  // One failed image cannot be labelled as a fully successful batch.
  const cid2=ensureConversation({kind:'canvas',title:'失败批次'}).id;
  let partialCalls=0;
  llm.completeToolChat=async()=>{ partialCalls++; if(partialCalls===2) throw Object.assign(new Error('failed'),{code:'MOCK_FAILURE'});return{content:[{type:'text',text:'可确认界面'}]};};
  delete require.cache[require.resolve('../lib/imageRecognition')];
  const partial=await require('../lib/imageRecognition').recognizeConversationImages({conversationId:cid2,messageId:999,images:images.slice(0,3)});
  assert.equal(partial.recognizedCount,2);assert.equal(partial.failedCount,1);
  const missing = await require('../lib/imageRecognition').recognizeConversationImages({conversationId:cid2,messageId:1001,images:[{...images[0],id:'missing',stored_name:'missing.png'},images[3]]});
  assert.equal(missing.recognizedCount,1);assert.equal(missing.failedCount,1);

  const cancel=new AbortController();cancel.abort();
  await assert.rejects(inspectImage(session,{ref},{signal:cancel.signal}),/abort/i);
  const beforeCancelled = getDb().prepare("SELECT COUNT(*) AS n FROM messages WHERE conversation_id=? AND type='parsed_attachment'").get(cid2).n;
  const during = new AbortController();
  llm.completeToolChat=async()=>{during.abort();return{content:[{type:'text',text:'不应保存'}]};};
  delete require.cache[require.resolve('../lib/imageRecognition')];
  await assert.rejects(require('../lib/imageRecognition').recognizeConversationImages({conversationId:cid2,messageId:1000,images:[images[4]],signal:during.signal}),/abort/i);
  assert.equal(getDb().prepare("SELECT COUNT(*) AS n FROM messages WHERE conversation_id=? AND type='parsed_attachment'").get(cid2).n,beforeCancelled);
  llm.completeToolChat=original;
  getDb().close();
}
main().then(()=>{console.log('agent materials/vision behavioral tests passed');fs.rmSync(root,{recursive:true,force:true});}).catch(error=>{console.error(error);process.exitCode=1;});
