const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8').replace(/\r\n/g, '\n');

const workspace = read('components/AgentWorkspace/AgentWorkspace.js');
const globalStyles = read('styles/globals.css');
const resourceEvents = read('utils/agentResourceEvents.js');
const controller = read('hooks/useAgentLoopController.js');
const startRoute = read('pages/api/agent/loop/start.js');
const cancelRoute = read('pages/api/agent/loop/cancel.js');
const conversationRoute = read('pages/api/conversations/[id].js');
const agentLoop = read('lib/agentLoop.js');
assert.ok(workspace.includes("if (parsed?.mode === 'server') return { mode: 'auto' };"));
assert.ok(workspace.includes("const mcpLabel = 'MCP';"));
assert.ok(workspace.includes("/api/settings/mcp/servers?enabled_only=1"));
assert.ok(workspace.includes("window.addEventListener('notus-mcp-servers-changed', onChanged);"));
assert.ok(workspace.includes("if (!mcpAvailabilityChecked || mcpAvailable || mcpMode !== 'auto') return;"));
assert.ok(workspace.includes('disabled={busy || disabled || !mcpAvailable}'), '没有可用 MCP Server 时按钮必须使用原生 disabled');
assert.ok(workspace.includes('aria-disabled={busy || disabled || !mcpAvailable}'));
assert.ok(workspace.includes("content={mcpAvailable ? 'MCP 工具' : '暂无 MCP 服务'}"));
assert.ok(workspace.includes('const toggleMcp = () => {'));
assert.ok(workspace.includes('onRequireMcpConfig?.();'));
assert.ok(workspace.includes("if (!mcpAvailabilityChecked || mcpAvailable || mcpMode !== 'auto') return;"));
assert.ok(workspace.includes("onMcpSelectionChange?.({ mode: 'auto' });"));
assert.ok(workspace.includes("onMcpSelectionChange?.({ mode: 'off' });"));
assert.ok(!workspace.includes('本次任务不提供外部 MCP 工具。'));
assert.ok(!workspace.includes('允许本次任务从已启用 Server 中自动选择相关工具。'));
assert.ok(workspace.includes('自动应用修改'));
assert.ok(workspace.includes('手动应用修改'));
assert.ok(workspace.includes("label: '自动'"), '确认方式的可见短标签应为“自动”');
assert.ok(workspace.includes("label: '手动'"), '确认方式的可见短标签应为“手动”');
assert.ok(!workspace.includes("label: '自动应用'"), '不应继续展示“自动应用”长标签');
assert.ok(!workspace.includes("label: '手动应用'"), '不应继续展示“手动应用”长标签');
assert.ok(!workspace.includes('Agent 完成后自动应用所有修改'));
assert.ok(!workspace.includes('Agent 完成后需逐文件手动确认'));
assert.ok(workspace.includes('const [modelQuery, setModelQuery] = useState(\'\');'));
assert.ok(workspace.includes('搜索模型或 Provider'));
assert.ok(workspace.includes('modelLabel(config), providerLabel(config), config?.name'));
assert.ok(workspace.includes('没有匹配的模型或 Provider'));

const drawer = read('components/ChatArea/ConversationDrawer.js');
assert.ok(drawer.includes('搜索对话或消息'));
assert.ok(drawer.includes('onSearchQueryChange'));
assert.ok(drawer.includes('function getCompactPreview(value, limit = 120)'), '历史搜索结果必须使用受限长度的摘要');
assert.ok(drawer.includes("replace(/\\s+/g, ' ')"), '历史搜索摘要必须合并换行和连续空白');

const fileWorkspace = read('components/AgentWorkspace/FileAgentWorkspace.js');
assert.ok(fileWorkspace.includes('control_ticket: targetSession.control_tickets?.resume'), '提问卡回答后的续跑必须携带目标 session 的 resume_session 控制票据');
assert.ok(fileWorkspace.includes('const queuedControlTicket = queuedSession?.control_tickets?.resume;'), '恢复历史 resume job 前必须取得所属 session 的 resume_session 控制票据');
assert.ok(fileWorkspace.includes('if (!queuedJob || !queuedControlTicket || autoResumedJobRef.current.has(queuedJob.id)) return;'), '缺少 resume_session 控制票据时不得误用 read 或 resume job 票据发起续跑');
assert.ok(fileWorkspace.includes('const [historySearchQuery, setHistorySearchQuery]'));
assert.ok(fileWorkspace.includes('const [restoringConversation, setRestoringConversation] = useState(false);'), '恢复状态首屏必须与服务端一致，避免 hydration 不匹配');
assert.ok(fileWorkspace.includes('if (savedId) setRestoringConversation(true);'), '客户端挂载后有保存会话时必须显示恢复提示');
assert.ok(fileWorkspace.includes('restoringConversation={restoringConversation}'), '文件工作区必须把恢复状态传给 Agent 面板');
assert.ok(fileWorkspace.includes("params.set('q', String(query).trim())"));
assert.ok(fileWorkspace.includes('没有匹配的历史对话'));
assert.ok(fileWorkspace.includes('agentLoopRef.current?.clearActiveAgentSession()'), '切换对话前必须解绑旧 Agent UI 状态');
assert.ok(/restoredConversationRef\.current = true;\r?\n    conversationLoadSequenceRef\.current \+= 1;/.test(fileWorkspace), '用户新建对话后不得被初始化中的旧对话恢复请求写回');
assert.ok(fileWorkspace.includes("const sessionLocked = agentLoop.activeAgentSession?.status === 'running'"), '可恢复等待状态不得永久禁用输入框');
assert.ok(fileWorkspace.includes('const [agentConfirmMode, setAgentConfirmMode] = useState(AUTO_CONFIRM);'), '确认模式首屏必须使用服务端与浏览器一致的默认值');
assert.ok(fileWorkspace.includes('setAgentConfirmMode(readConfirmMode());'), '浏览器挂载后必须恢复本地确认模式偏好');
assert.ok(!fileWorkspace.includes('useState(() => readConfirmMode())'), '确认模式不得在 Hydration 初始化阶段读取 localStorage');
assert.ok(fileWorkspace.includes('shouldClearAgentPresentation({'), '空历史会话只能在没有实时任务 UI 时清理');
assert.ok(fileWorkspace.includes('restoreAgentSession(null);'), '没有已恢复会话和实时任务时仍必须清掉旧 session 锁');
assert.ok(fileWorkspace.includes('agentPresentationRef.current.activeSteps'), '恢复副作用应读取实时展示快照，而非订阅步骤数组变化');
assert.ok(fileWorkspace.includes("if (session && !agentLoop.loading && !activeAgentSessionId)"), '历史恢复不能覆盖当前新建 session 的实时工具记录');
assert.ok(!fileWorkspace.includes('}, [agentLoop.activeAgentSession, agentLoop.activeSteps, agentLoop.streamText, agentResumeJobs,'), '恢复副作用不能订阅自身会改写的展示状态');
assert.ok(fileWorkspace.includes('!agentLoop.loading && shouldClearAgentPresentation({'), '新任务请求尚在创建时不能被空历史恢复逻辑清空');
assert.ok(!fileWorkspace.includes('disabled={agentLoop.loading || sessionLocked} onClick={handleNewConversation}'), '任务中断或运行时也必须允许新建对话');
assert.ok(controller.includes('runSequenceRef.current += 1;'));
assert.ok(controller.includes('setLoading(false);'));
assert.ok(controller.includes("setSteps((steps) => (Array.isArray(steps) && steps.length === 0 ? steps : []));"), '清空步骤必须保留已有空数组引用');
assert.ok(controller.includes("mcp_selection: input?.mcp_selection ?? input?.mcpSelection ?? { mode: 'off' }"), '新任务请求必须把输入框的 MCP 自动选择传给服务端');
assert.ok(controller.includes('hide_user_message_bubble: Boolean(input?.hide_user_message_bubble ?? input?.hideUserMessageBubble)'), '新任务请求和乐观消息必须传递仅媒体消息的隐藏气泡标记');
assert.ok(startRoute.includes("require('../../../../lib/directLoopbackRequest')"), '本机 HTTP MCP 必须使用服务端直接回环来源判定');
assert.ok(startRoute.includes('mcpSessionPermissions: { allow_local_http: allowsLocalHttpMcp(req) }'), '服务端必须将本机 HTTP 许可存入独立 session 权限，而非客户端 MCP 选择');
assert.ok(startRoute.includes('supersedePendingUserActionTasks(conversation.id)'), '新 prompt 必须先解除同一对话的等待任务，避免 FIFO 永久阻塞');
assert.ok(startRoute.includes('hide_user_message_bubble: Boolean(body.hide_user_message_bubble ?? body.hideUserMessageBubble)'), '服务端持久化的用户消息必须保留隐藏气泡标记，刷新历史后仍然生效');
assert.ok(controller.includes('buildRestoredAgentTimeline(session)'));
assert.ok(controller.includes('export function buildRestoredAgentTimeline(session = {})'), '会话恢复时间线需要供文件工作区重建全部历史记录');
assert.ok(controller.includes('finishRunningStep(step)'), '已完成会话遗留的运行步骤必须恢复为完成而非中断');
assert.ok(controller.includes("label: '任务已暂停，执行记录已保留'"));
assert.ok(controller.includes("setStreamText(session.status === 'completed' ? '' : restored.draft);"), '已完成会话不能恢复中断前草稿');
assert.ok(fileWorkspace.includes("['failed', 'cancelled'].includes(item.status)"));
assert.ok(fileWorkspace.includes("item.status === 'completed' && hasPersistedTimeline(item)"), '已完成且带持久化事件的会话也必须恢复执行记录');
assert.ok(fileWorkspace.includes('function timelineFromSession(session = {})'), '文件工作区必须为每个已恢复 session 构建独立工具记录');
assert.ok(fileWorkspace.includes('const [liveSessionTimelines, setLiveSessionTimelines] = useState({});'), '文件工作区必须保存每个实时 session 的工具记录映射');
assert.ok(fileWorkspace.includes('function mergeSessionTimeline(restored = {}, live = {})'), '刷新后的 SSE 时间线必须与已恢复步骤合并');
assert.ok(fileWorkspace.includes('let activeSteps = liveSteps.reduce((steps, step) => upsertById(steps, step), restoredSteps);'), '实时增量不得用空步骤数组覆盖刷新前的持久化执行记录');
assert.ok(fileWorkspace.includes("if (['completed', 'failed', 'cancelled'].includes(String(live?.sessionStatus || '')))"), '终态到达后必须清除仅用于非终态恢复的暂停提示');
assert.ok(fileWorkspace.includes("step?.id !== 'resume-interrupted-task'"), '终态时间线不得继续显示可恢复暂停步骤');
assert.ok(fileWorkspace.includes('merged[sessionId] = mergeSessionTimeline(merged[sessionId], timeline);'), '会话时间线必须按 session 合并恢复记录与实时增量');
assert.ok(fileWorkspace.includes('const operationSetBySessionId = useMemo'), '完成态 Diff 卡必须可按 Agent session 回退关联，兼容早期缺失 operation_set_id 的最终消息');
assert.ok(fileWorkspace.includes('operationSetById[operationSetId] || operationSetBySessionId[sessionId]'), '消息级 Diff 恢复必须优先按操作集 ID，再按 session 关联');
assert.ok(fileWorkspace.includes('onSessionTimeline: handleSessionTimeline'), '每个订阅会话的实时事件都必须写入独立时间线');
assert.ok(fileWorkspace.includes('Object.entries(liveSessionTimelines).forEach'), '已恢复和实时 session 的时间线必须合并展示');
assert.ok(fileWorkspace.includes('userMessageId: Number(session?.task?.user_message_id'), '历史等待任务必须绑定到其原始用户消息');
assert.ok(workspace.includes('中断前已生成的回复'));
assert.ok(workspace.includes('function AgentTaskTimeline'));
assert.ok(workspace.includes('function mergeAgentTimelineSteps(restoredSteps = [], activeSteps = [])'), '当前 session 必须合并刷新前的恢复步骤和控制器实时步骤');
assert.ok(workspace.includes('const currentTimeline = currentTimelineSource || hasAgentActivity ? {'), '控制器进入终态后仍必须保留当前 session 的持久化时间线');
assert.ok(workspace.includes('activeSteps: mergeAgentTimelineSteps(currentTimelineSource?.activeSteps, activeSteps)'), '空的控制器步骤不得覆盖刷新前已恢复的执行记录');
assert.ok(workspace.includes('const hasAgentActivity = hasPersistedTimeline || Boolean(streamText) || Boolean(error) || Boolean(loading)'));
assert.ok(workspace.includes('function AgentErrorCard'), 'Agent 中断错误必须使用统一错误信息组件');
assert.ok(controller.includes('newTaskSubmitInFlightRef'), '新任务提交在服务端受理前必须有同步防重锁');
assert.ok(workspace.includes('className="notus-agent-error-card"'), '错误信息组件必须使用独立卡片结构');
assert.ok(workspace.includes('mediaItems: sourceMediaItems'), '消息重试必须保留完整媒体顺序');
assert.ok(workspace.includes('images: sourceImages'), '消息重试必须保留图片载荷');
assert.ok(workspace.includes('actionDisabled={Boolean(disabled)}'), '任务进行中的 loading 不能整体禁用历史消息操作');
assert.ok(!workspace.includes('actionDisabled={Boolean(disabled) || Boolean(loading)}'), '消息改写和重试不能与 Agent 运行状态联动');
const userMessageRowSource = workspace.slice(workspace.indexOf('function UserMessageRow'), workspace.indexOf('function MessageTimestamp'));
assert.ok(userMessageRowSource.includes('CopyMessageButton text={displayContent} disabled={false}'), '用户消息复制是本地操作，不能因 Agent 或模型状态禁用');
assert.ok(userMessageRowSource.includes('const hideUserMessageBubble = Boolean(message?.meta?.hide_user_message_bubble);'), '仅上传媒体的用户消息必须由持久化标记控制气泡隐藏');
assert.ok(userMessageRowSource.includes('const hasTextContent = !hideUserMessageBubble'), '仅上传媒体时不得渲染合成任务文案的用户消息气泡');
assert.ok(workspace.includes('hideUserMessageBubble,'), '输入框提交仅媒体任务时必须传递隐藏气泡标记');
assert.ok(workspace.includes('errorType: \'agent\''), 'LLM 和请求级错误必须标记为 Agent 错误节点');
assert.ok(globalStyles.includes('.notus-agent-error-card__footer'), '错误卡片必须拥有与 Diff 详情一致的底部操作区');
assert.ok(globalStyles.includes('box-shadow: none;'), '错误卡片不得保留底部投影');
assert.ok(workspace.includes("step?.errorType !== 'agent' && step?.kind !== 'segment'"), 'Agent 错误和内部执行段都不能进入带分隔线的普通工具步骤列表');
assert.ok(!globalStyles.includes('.notus-agent-toolchain__steps.has-agent-error'), '错误卡片不应通过状态类隐藏外层边框');
assert.ok(!workspace.includes('重试会重新发送上一条用户消息及其 Mention、附件和图片。'), '错误卡片不应在按钮区重复说明重试载荷');
assert.ok(globalStyles.includes('justify-content: flex-end;'), '错误卡片操作按钮必须对齐到右下角');
assert.ok(globalStyles.includes('.notus-agent-error-card__footer {'), '错误卡片按钮区必须保留独立布局容器');
assert.ok(workspace.includes("sessionStatus === 'queued'"), '任务受理后必须在工具链头部显示排队/运行状态');
assert.ok(workspace.includes('已等待 ${elapsed}'), '任务受理后必须立即开始展示已等待时长');
assert.ok(workspace.includes('startedAt={timeline.startedAt || \'\'}'), '实时任务的起始时间必须传入工具链以驱动计时');
assert.ok(workspace.includes('finishedAt={timeline.finishedAt || \'\'}'), '已结束任务的结束时间必须传入工具链以计算完整耗时');
assert.ok(workspace.includes('const taskStartedAt = traceTimestamp(startedAt);'), '工具链必须优先使用任务开始时间，而非第一个可见工具步骤');
assert.ok(workspace.includes('const taskFinishedAt = traceTimestamp(finishedAt);'), '工具链必须优先使用任务结束时间，而非最后一个可见工具步骤');
assert.ok(fileWorkspace.includes("const startedAt = session?.task?.started_at || '';"), '历史任务必须把队列的真实开始时间传给工具链');
assert.ok(fileWorkspace.includes("const finishedAt = session?.task?.finished_at || session?.task?.updated_at || '';"), '历史任务必须把队列的真实结束时间传给工具链');
assert.ok(workspace.includes('notus-agent-toolchain__step--enter'), '真实工具步骤必须具备逐条入场样式');
assert.ok(globalStyles.includes('@keyframes notus-agent-tool-step-in'), '工具步骤必须定义入场动画');
assert.ok(globalStyles.includes('animation-delay: calc(var(--notus-step-index, 0) * 70ms);'), '同批抵达的工具步骤必须以小间隔依次呈现');
assert.ok(workspace.includes('if (messages.length === 0 && !hasAgentActivity)'));
assert.ok(workspace.includes('<div className="notus-agent-task-timeline">'));
assert.ok(!workspace.includes('className="notus-agent-task-timeline__identity"'));
assert.ok(!workspace.includes('.notus-agent-task-timeline__avatar'));
assert.ok(!globalStyles.includes('.notus-agent-task-timeline__avatar'));
assert.ok(workspace.includes('内部循环、排队和推测性 loading 不进入执行记录'));
assert.ok(workspace.includes('function ToolTraceIcon'));
assert.ok(workspace.includes("const FILE_READ_TOOL_NAMES = new Set(['read_file', 'read_global_agent_file']);"), '文件读取工具必须使用显式语义映射');
assert.ok(workspace.includes('if (FILE_READ_TOOL_NAMES.has(toolName)) return <Icons.fileText size={size} />;'), '文件读取工具必须显示带文本行的文件图标');
assert.ok(workspace.includes('if (FILE_WRITE_TOOL_NAMES.has(toolName)) return <Icons.fileEdit size={size} />;'), '文件写入和修改预览必须显示文件编辑图标');
assert.ok(workspace.includes("if (source.includes('mcp')) return <Icons.mcp size={size} />;"), 'MCP 工具必须优先使用独立服务器机架图标');
assert.ok(workspace.includes("if (source.includes('skill')) return <Icons.skill size={size} />;"), 'Skill 工具必须优先使用独立 Skill 图标');
assert.ok(workspace.includes('executionTrace={messageTimeline'), '助手回复需要优先使用与自身 session 关联的执行记录');
assert.ok(workspace.includes('>{revisionCount} 个文件修订</div>'), '累计 Diff 卡主描述必须只显示文件修订数量');
assert.ok(workspace.includes("`已应用 ${appliedCount} 个`"), '累计 Diff 卡次描述必须显示已应用数量');
assert.ok(workspace.includes("`已回滚 ${rolledBackCount} 个`"), '累计 Diff 卡次描述必须显示已回滚数量');
assert.ok(workspace.includes("`已废弃 ${discardedCount} 个`"), '累计 Diff 卡次描述必须显示已废弃数量');
assert.ok(workspace.includes("borderRadius: '50%'"), '累计 Diff 卡修订图标外框必须为圆形');
assert.ok(workspace.includes(".filter((timeline) => String(timeline?.userMessageId || '') === String(message.id || ''))"), '未完成任务必须按 user_message_id 附着到原始用户消息');
assert.ok(workspace.includes('const messageSessionKey = String(message?.meta?.session_id || \'\');'), '已完成任务必须按 assistant meta.session_id 附着到对应回复');
const toolChainSource = workspace.slice(workspace.indexOf('function ToolChain'), workspace.indexOf('function operationItems'));
assert.ok(!toolChainSource.includes('ToolStatusIcon'), '工具行不得使用 loading 转圈或完成对勾状态图标');
assert.ok(!toolChainSource.includes('Icons.check'), '工具行不得展示完成对勾');
assert.ok(toolChainSource.includes('<Icons.chevronRight size={15} aria-hidden="true" />'), '处理时长概览右侧必须使用朝右箭头，展开状态由 aria-expanded 表达');
assert.ok(toolChainSource.includes('<ToolPayload label="调用参数" value={step.input} />'), '工具详情必须为参数提供独立阅读区域');
assert.ok(toolChainSource.includes('<ToolPayload label="调用结果" value={step.result} />'), '工具详情必须为结果提供独立阅读区域');
assert.ok(workspace.includes('function formatToolPayload(value)'), '工具 JSON 必须在前端格式化后显示');
assert.ok(workspace.includes('正在恢复上次对话…'), '恢复期间不得显示空白消息区');
assert.ok(!toolChainSource.includes('<Icons.chevronDown size={15} className={traceExpanded'), '处理时长概览不得把向下箭头旋转成向左箭头');
assert.ok(!workspace.includes("{ id: 'prepare', label: '准备上下文'"));
assert.ok(!controller.includes('任务已加入后台执行'));
assert.ok(!controller.includes('执行第 ${loop ||'), '内部循环轮次不得写入工具链');
assert.ok(controller.includes("label: '等待确认修改预览',\n      status: 'waiting'"), '等待预览不能伪装成已处理');
assert.ok(controller.includes("label: '等待回答提问卡片',\n      status: 'waiting'"), '等待提问不能伪装成已处理');
assert.ok(toolChainSource.includes('const hasActionRequired'), '工具链头部必须将等待用户操作显示为需要处理');
assert.ok(toolChainSource.includes("const isCancelled = sessionStatus === 'cancelled' || tailStatus === 'cancelled';"), '已取消任务必须与需要处理状态分开');
assert.ok(toolChainSource.includes("isCancelled\n    ? '已取消'"), '已取消任务的执行记录标题必须显示已取消');
assert.ok(controller.includes("step.id?.startsWith('operation-confirmation-')"), '任务完成后必须结束已处理的文件确认步骤，避免继续显示需要处理');
assert.ok(controller.includes('completeSteps(activeSteps, { resolveOperationConfirmations: true })'), '实时 final 事件必须结束已处理的文件确认步骤');
assert.ok(controller.includes('completeSteps(steps, { resolveOperationConfirmations: true })'), '历史 completed 会话必须结束已处理的文件确认步骤');
assert.ok(controller.includes('export function applyAgentTimelineEvent'), '并发 session 必须按事件独立更新自己的时间线');
assert.ok(controller.includes('controllersRef.current.add(controller);'), '新任务入队不得中断旧任务的 SSE 订阅');
assert.ok(!controller.includes('tool_input_summary: row.tool_input'), '旧运行日志不得将原始工具参数带回页面');
assert.ok(controller.includes("result_summary: '历史工具调用已完成（原始参数和结果未显示）'"), '旧运行日志必须使用隐私保护摘要');
assert.ok(!controller.includes('legacyLogs.forEach((row) => {'), '旧运行日志不得恢复未经统一脱敏的 thinking 草稿');
assert.ok(toolChainSource.includes("onAction(step.action, step, sessionId)"), '工具记录操作必须携带所属 session');
assert.ok(globalStyles.includes('.notus-agent-toolchain__label {\n  min-width: 0;\n  flex: 0 1 auto;') && globalStyles.includes('overflow-wrap: anywhere;'), '工具名称必须优先完整展示，不能被长结果摘要挤压成单字，超长名称应换行显示');
assert.ok(!toolChainSource.includes('<span className="notus-agent-toolchain__summary"'), '折叠工具行不能显示工具结果摘要');
assert.ok(globalStyles.includes('.notus-agent-toolchain__icon {\n  flex: 0 0 18px;') && globalStyles.includes('color: var(--accent);'), '所有工具图标必须使用 Notus 主色');
assert.ok(workspace.includes('onResumeAgentTask?.(sessionId)'), '继续任务必须将目标 session 传回文件工作区');
assert.ok(fileWorkspace.includes('resumeFailedAgentTask = useCallback(async (targetSessionId = null)'), '文件工作区必须按点击的 session 恢复任务');
assert.ok(workspace.includes("if (action === 'stop_agent') void onStop?.(sessionId);"));
assert.ok(!workspace.includes("{loading ? <button type=\"button\" aria-label=\"停止当前任务\" onClick={() => onStop?.()}"));
assert.ok(workspace.includes('onInterrupt={onStop}'), '输入框中断必须复用按 session 精确取消的回调');
assert.ok(workspace.includes('interruptibleSessionId={interruptibleSessionId}'), '输入框必须接收当前可中断任务的 session ID');
assert.ok(workspace.includes("aria-label={canInterrupt ? '中断当前任务' : '发送'}"), '运行任务时发送按钮必须切换为中断按钮');
assert.ok(workspace.includes('void onInterrupt(interruptibleSessionId);'), '中断按钮必须传递当前任务的 session ID');
assert.ok(workspace.includes('<Icons.square size={16} />'), '中断按钮必须使用停止图标');
assert.ok(fileWorkspace.includes("const INTERRUPTIBLE_AGENT_SESSION_STATUSES = new Set(['created', 'queued', 'running']);"), '只有可取消的在途任务才会切换输入按钮');
assert.ok(fileWorkspace.includes('const interruptibleSessionId = useMemo(() => {'), '切回历史对话后必须从已恢复任务重新识别可中断 session');
assert.ok(fileWorkspace.includes('const registerAgentSessions = agentLoop.registerAgentSessions;') && fileWorkspace.includes('registerAgentSessions(restoredAgentSessions);'), '恢复列表中的可中断任务必须同步给取消控制器，避免多个任务时只能拿到 ID 不能取消');
assert.ok(fileWorkspace.includes('const liveStatus = sessionId ? liveSessionTimelines[sessionId]?.sessionStatus : \'\';'), '恢复任务收到终态事件后必须以实时状态覆盖旧的恢复状态');
assert.ok(fileWorkspace.includes('interruptibleSessionId={interruptibleSessionId}'), '文件工作区必须把可中断 session 传入输入框');
assert.ok(fileWorkspace.includes("return { ...session, status: activeStatus || liveStatus || session?.status || '' };"), '本地取消状态必须优先于恢复列表和实时订阅状态，避免重复中断');
assert.ok(controller.includes("updateAffectedSessions('cancelling');"), '取消请求尚未确认时必须移除该对话全部在途任务的中断状态');
assert.ok(controller.includes('const registerAgentSessions = useCallback((sessions = []) => {'), '取消控制器必须登记恢复的全部任务，而非只登记当前展示任务');
assert.ok(controller.includes('sessions: affectedSessionIds.map'), '输入框中断任务时必须逐项携带取消凭据，才能同时结束该对话内其他在途任务');
assert.ok(controller.includes('cancelled_session_ids'), '批量取消响应必须逐个同步为终态，不能让恢复列表继续显示为运行中');
assert.ok(cancelRoute.includes('requestedSessions') && cancelRoute.includes('sessionsById'), '取消接口必须逐项验证并去重批量取消请求');
assert.ok(cancelRoute.includes("action: 'cancel' }, { consume: true }"), '批量取消必须只在全部凭据通过预检后消耗对应 cancel ticket');
assert.ok(conversationRoute.includes("['created', 'queued', 'running'"), '恢复的排队任务必须重新签发 cancel ticket，不能只给前端一个无法取消的 session ID');
assert.ok(controller.includes("if (!response.ok) throw new Error(await readErrorResponse(response, '中断 Agent 任务失败'));"), '取消接口失败时不得伪装成已取消');
assert.ok(workspace.includes('className="notus-agent-composer-dock"'));
assert.ok(workspace.includes('className="notus-agent-composer__model"'));
assert.ok(workspace.includes('className="notus-agent-composer__attachments"'), '窄面板须将附件操作作为独立分组');
assert.ok(!workspace.includes('className="notus-agent-composer__task-controls"'), '确认方式与联网工具不能再被嵌套分组强制拆成三行');
const composerToolbarSource = workspace.slice(workspace.indexOf('className="notus-agent-composer__tools"'), workspace.indexOf('className="notus-agent-composer__actions"'));
assert.ok(composerToolbarSource.indexOf('className="notus-agent-composer__attachments"') < composerToolbarSource.indexOf('AgentConfirmModeSelect') && composerToolbarSource.indexOf('AgentConfirmModeSelect') < composerToolbarSource.indexOf('className="notus-agent-composer__network-tools"'), '确认方式、附件与联网工具必须是工具栏直接子项，便于最窄宽度按区域布局');
assert.ok(globalStyles.includes('.notus-agent-composer__tools {\n    flex: 1 1 auto;\n    flex-wrap: nowrap;'), '窄面板工具区须把左下工具列收敛为单行');
assert.ok(globalStyles.includes('max-width: calc(100% - 108px);\n    overflow: visible;'), '窄面板工具区不能裁剪向上弹出的 MCP 和模型菜单');
assert.ok(globalStyles.includes('.notus-agent-confirm-mode .notus-segmented-tabs__label {\n    display: none;'), '确认方式在窄面板必须收敛为 icon');
assert.ok(globalStyles.includes('.notus-agent-control-label {\n    display: none;'), '窄面板只收敛联网和 MCP 文案');
const narrowComposerStyles = globalStyles.slice(globalStyles.indexOf('@container notus-agent-workspace (max-width: 390px)'), globalStyles.indexOf('@keyframes shimmer'));
assert.ok(narrowComposerStyles.includes("grid-template-areas:\n      'attachments network'\n      'confirm confirm';"), '最小 AI 面板宽度下附件与联网工具必须位于首行，确认方式独占次行');
assert.ok(narrowComposerStyles.includes('.notus-agent-confirm-mode {\n    grid-area: confirm;\n    justify-self: start;\n    width: fit-content;'), '确认方式在最窄面板应保持紧凑 icon Tab，而非拉伸占满整行');
assert.ok(!narrowComposerStyles.includes('.notus-segmented-tabs__label'), '最小 AI 面板宽度下确认方式不得恢复文字标签');
assert.ok(narrowComposerStyles.includes('overflow-x: hidden !important;'), '确认方式 Tab 已适配最小宽度后不应保留横向滚动条');
assert.ok(!narrowComposerStyles.includes('order:'), '确认方式换行时不得通过 order 重排控件');
assert.ok(narrowComposerStyles.includes('flex: 0 0 28px;'), '最小宽度下两个确认方式 Tab 必须保持图标紧凑宽度');
assert.ok(globalStyles.includes('gap: 0 !important;'), '确认方式在窄面板仅显示 icon 时不得保留文字间距');
assert.ok(workspace.includes("ariaLabel: option.value === 'auto_confirm' ? '自动应用修改' : '手动应用修改'"), '确认方式收敛为 icon 后仍须保留无障碍名称');
assert.ok(globalStyles.includes('.notus-agent-composer__model {\n    max-width: 96px;'), '窄面板模型选择须缩略显示');
assert.ok(!globalStyles.includes('.notus-agent-composer__tools > * {\n    flex: 0 0 auto;'), '窄面板工具区不得强制所有控制横向滚动');
assert.ok(workspace.includes('showJumpToBottom = false, onJumpToBottom'), '回底控制必须由输入停靠区接收，避免覆盖消息滚动层');
assert.ok(workspace.includes('className="notus-agent-composer__jump-to-bottom notus-agent-pressable"'), '回底控制必须渲染在输入停靠区的正常文档流中');
assert.ok(!workspace.includes('CHAT_JUMP_BUTTON_OFFSET'), '回底控制不得继续使用固定绝对偏移覆盖工具链内容');
assert.ok(globalStyles.includes('.notus-agent-composer__jump-to-bottom {\n  display: flex !important;\n  margin: 0 12px 8px auto !important;'), '回底按钮必须停靠在输入区右侧，避免压住工具链中部文字');
assert.ok(narrowComposerStyles.includes('padding-bottom: 278px;'), '最窄面板的消息区必须为扩展后的输入停靠区预留安全空间');
assert.ok(controller.includes("label: '正在思考'"), '模型可见执行说明在工具链中必须显示为“正在思考”。');
assert.ok(controller.includes("if (event.type === 'model_progress')"), '模型可见执行说明必须由同一 session timeline 恢复。');
assert.ok(controller.includes("event.stage === 'thinking'"), '旧 thinking 草稿只能用于兼容中断回复，不能与模型执行说明重复渲染。');
assert.ok(controller.includes('setStreamText(assistantTextRef.current);'), '异常收尾不得清空已生成回复草稿');
assert.ok(agentLoop.includes('let latestOperationSetId = null;'), '自动应用文件修订后必须保留最新变更集 ID');
assert.ok(agentLoop.includes('operation_set_id: latestOperationSetId'), '模型继续生成最终总结时也必须把变更集关联到最终消息');

const conversations = read('lib/conversations.js');
assert.ok(conversations.includes('LOWER(c.title) LIKE ?'));
assert.ok(conversations.includes('EXISTS ('));
assert.ok(conversations.includes("m.role IN ('user', 'assistant')"));
assert.ok(conversations.includes('LOWER(m.content) LIKE ?'));

const conversationsApi = read('pages/api/conversations/index.js');
assert.ok(conversationsApi.includes('req.query.q'));

const layout = read('components/ui/ResizableLayout.js');
const filesPage = read('pages/files/index.js');
const sidebar = read('components/Layout/Sidebar.js');
assert.ok(layout.includes('fixedRightPx = 0'));
assert.ok(layout.includes('const hasFixedRight'));
assert.ok(filesPage.includes('const FILES_AGENT_FIXED_WIDTH = 456;'));
assert.ok(filesPage.includes("const FILES_EDITOR_AUTO_COLLAPSE_QUERY = '(max-width: 760px)'"));
assert.ok(filesPage.includes('const [editorAutoCollapsed, setEditorAutoCollapsed]'));
assert.ok(filesPage.includes('fixedRightPx={agentFixedWidthViewport ? FILES_AGENT_FIXED_WIDTH : 0}'));
assert.ok(sidebar.includes('const [autoCollapsed, setAutoCollapsed]'));
assert.ok(sidebar.includes('const isSidebarCollapsed = autoCollapsed ||'));

const settings = read('components/Settings/SettingsScreen.js');
assert.ok(settings.includes("new Event('notus-mcp-servers-changed')"));
assert.ok(settings.includes("{ id: 'global-agent', label: 'Agent 个性', icon: <Icons.brain"));
assert.ok(settings.includes("{ id: 'skills', label: 'Skill', icon: <Icons.skill"));
assert.ok(resourceEvents.includes("'install_skill_from_git'"));
assert.ok(resourceEvents.includes("'skill_uninstall'"));
assert.ok(resourceEvents.includes("'add_mcp_server'"));
assert.ok(resourceEvents.includes("'mcp_remove'"));
assert.ok(controller.includes("dispatchAgentResourceChange(event.tool_name)"));
assert.ok(fileWorkspace.includes("dispatchAgentResourceChange(interaction?.payload?.action)"));
assert.ok(workspace.includes("if (!Number.isFinite(duration) || duration < 1000) return '1 秒';"), '短任务的工具链时长应显示为 1 秒');
assert.ok(workspace.includes("? `正在处理${elapsed ? ` ${elapsed}` : ''}`"), '运行中的工具链应显示“正在处理 x 秒”');
assert.ok(!workspace.includes('Math.max(0, Math.round(Number(milliseconds || 0) / 1000))'), '工具链时长不能继续用会把短任务四舍五入为 0 的计算方式');

console.log('agent workspace controls tests passed');
